config/routes.rb
Rails.application.routes.draw do

  root "friends#index"
  resources :friends

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  validates :first_name, :last_name, 
  :phone_number, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, 
        :last_name, :phone_number, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :phone_number %>
        <%= form.text_field :phone_number, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="container my-5">

  <h1>Editing Friend</h1>

  <%= render 'form', friend: @friend %>

  <button type = button class="btn btn-success"><%= link_to 'Show', @friend %></button>
  <button type = button class="btn btn-success"><%= link_to 'Back', friends_path %></button>
</div>

app/views/friends/index.html.erb
<div class="container my-5">
  <p id="notice"><%= notice %></p>

  <h1>Friends</h1>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Phone number</th>
        <th scope="col">Address</th>
        <th scope="col" colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.phone_number %></td>
          <td><%= friend.address %></td>
          <td><button type="button" class="btn btn-success"><%= link_to 'Show', friend %></button></td>
          <td><button type="button" class="btn btn-success"><%= link_to 'Edit', edit_friend_path(friend) %></button></td>
          <td><button type="button" class="btn btn-success"><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <button type="button" class="btn btn-success"><%= link_to 'New Friend', new_friend_path %></button>
</div>

app/views/friends/new.html.erb
<div class="container my-5">
  <h1>New Friend</h1>

  <button type="button btn-success"><%= render 'form', friend: @friend %></button>
  <button type="button btn-success"><%= link_to 'Back', friends_path %></button>
</div>

app/views/friends/show.html.erb
<div class="container my-5">
  <p id="notice"><%= notice %></p>

  <div class="card text-center">
    <div class="card-header">
      Friend
    </div>

    <div class="card-body">
      <p>
        <strong>First name:</strong>
        <%= @friend.first_name %>
      </p>

      <p>
        <strong>Last name:</strong>
        <%= @friend.last_name %>
      </p>

      <p>
        <strong>Phone number:</strong>
        <%= @friend.phone_number %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @friend.address %>
      </p>
    </div>

    <div class="card-footer text-muted">
      <button type="button" class="btn btn-success"><%= link_to 'Edit', edit_friend_path(@friend) %></button>
      <button type="button" class="btn btn-success"><%= link_to 'Back', friends_path %></button>
    </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>